#### docker run -it -v /home/aravinda-weerasekara/Projects/allure-docker/allure-results/:/home/allure-results --name allure-docker allure /bin/bash
### docker-compose up -d allure

version: '3'
services:
  allure:
    image: "allure"
    user: "0:0"
    container_name: "Allure-docker"
    ports:
      - "8000:8080"
    volumes:
      - /home/aravinda-weerasekara/Documents/allure-results/:/home/results
      - /home/aravinda-weerasekara/Documents/allure-reports/:/home/allure-report
      - /home/aravinda-weerasekara/Documents/allure-result_BACKUP/:/home/backup